"""Generate only this project's MCP config with absolute paths; never edit user config."""
import argparse
import json
from pathlib import Path
import sys
import tomllib


def configure(workspace: Path, python: Path) -> Path:
    workspace, python = workspace.resolve(), python.resolve()
    target = workspace / ".codex" / "config.toml"
    marker = "# Generated by moex-analyst; contains machine-local paths."
    if target.exists() and not target.read_text(encoding="utf-8").startswith(marker):
        raise RuntimeError("Existing custom .codex/config.toml was preserved. Merge config/codex.example.toml manually.")
    lines = [marker, ""]
    for service in ["market", "documents", "research"]:
        args = ["-m", "moex_analyst.mcp_server", "--service", service, "--workspace", str(workspace)]
        lines += [f"[mcp_servers.moex_{service}]", f"command = {json.dumps(str(python))}",
                  f"args = {json.dumps(args)}", f"cwd = {json.dumps(str(workspace))}",
                  "startup_timeout_sec = 30", "tool_timeout_sec = 180", ""]
    content = "\n".join(lines)
    tomllib.loads(content)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--workspace", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--python", type=Path, default=Path(sys.executable))
    args = p.parse_args()
    print(configure(args.workspace, args.python))
